[package]
name = "SqueakSS_Dencoders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
md5 = "0.7.0"
urlencoding = "1.1.1"